platform :ios,’8.0’
use_frameworks!
xcodeproj 'BrokenLineView.xcodeproj'
target 'BrokenLineView' do
    pod 'Masonry'
    pod 'ReactiveObjC'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end
